#!/bin/bash

_nbfc() {
  local cur prev words cword split args w
  _init_completion -s || return

  _count_args "" ""
  for w in "${COMP_WORDS[@]}"; do
    case "$w" in
      start) _nbfc_start && return 0;;
      stop) _nbfc_stop && return 0;;
      restart) _nbfc_restart && return 0;;
      status) _nbfc_status && return 0;;
      config) _nbfc_config && return 0;;
      set) _nbfc_set && return 0;;
      help) _nbfc_help && return 0;;
    esac
  done

  if [[ "$cur" = -* ]]; then
    COMPREPLY+=($(compgen -W '-h --help' -- "$cur"))
  fi

  case $args in
    1)
       COMPREPLY+=($(compgen -W 'start stop restart status config set help' -- "$cur"));
       return 0;;
  esac

  return 1
}

_nbfc_start() {
  if [[ "$cur" = -* ]]; then
    COMPREPLY+=($(compgen -W '-h --help -e --enabled -r --readonly' -- "$cur"))
  fi

  return 1
}

_nbfc_stop() {
  if [[ "$cur" = -* ]]; then
    COMPREPLY+=($(compgen -W '-h --help' -- "$cur"))
  fi

  return 1
}

_nbfc_restart() {
  if [[ "$cur" = -* ]]; then
    COMPREPLY+=($(compgen -W '-h --help -e --enabled -r --readonly' -- "$cur"))
  fi

  return 1
}

_nbfc_status() {
  case "$prev" in
    -f|--fan)
       COMPREPLY=($(compgen -W "{0..255}" -- "$cur"));
       return 0;;
    -w|--watch)
       COMPREPLY=();
       return 0;;
  esac

  if [[ "$cur" = -* ]]; then
    COMPREPLY+=($(compgen -W '-h --help -a --all -s --service -f --fan -w --watch' -- "$cur"))
  fi

  return 1
}

_nbfc_config() {
  case "$prev" in
    -s|--set)
       COMPREPLY=();
       return 0;;
    -a|--apply)
       COMPREPLY=();
       return 0;;
  esac

  if [[ "$cur" = -* ]]; then
    COMPREPLY+=($(compgen -W '-h --help -l --list -s --set -a --apply -r --recommend' -- "$cur"))
  fi

  return 1
}

_nbfc_set() {
  case "$prev" in
    -s|--speed)
       COMPREPLY=();
       return 0;;
    -f|--fan)
       COMPREPLY=($(compgen -W "{0..255}" -- "$cur"));
       return 0;;
  esac

  if [[ "$cur" = -* ]]; then
    COMPREPLY+=($(compgen -W '-h --help -a --auto -s --speed -f --fan' -- "$cur"))
  fi

  return 1
}

_nbfc_help() {
  if [[ "$cur" = -* ]]; then
    COMPREPLY+=($(compgen -W '-h --help' -- "$cur"))
  fi

  return 1
}

complete -F _nbfc nbfc
