#!/bin/bash

_nbfc_service() {
  local cur prev words cword split args w
  _init_completion -s || return

  case "$prev" in
    -c|--config-file)
       COMPREPLY=();
       return 0;;
    -s|--state-file)
       COMPREPLY=();
       return 0;;
    -e|--embedded-controller)
       COMPREPLY=($(compgen -W 'dummy ec_linux ec_sys_linux' -- "$cur"));
       return 0;;
  esac

  if [[ "$cur" = -* ]]; then
    COMPREPLY+=($(compgen -W '-h --help -r --readonly -f --fork -d --debug -c --config-file -s --state-file -e --embedded-controller' -- "$cur"))
  fi

  return 1
}

complete -F _nbfc_service nbfc_service
